// config/platformPages.ts
//
// Data source for PostMaker's platform-specific landing pages (/tools/:slug).
// Auto-generated by scripts/generate_platform_pages.ts to support all 33 platforms.
// Follows the exact extension-point pattern of vsPages.ts and forPages.ts.

export interface PlatformFeature {
  title: string
  description: string
}

export interface PlatformFAQ {
  question: string
  answer: string
}

export interface PlatformPageEntry {
  /** URL slug, resolves to /tools/:slug */
  slug: string
  /** References the platform.id from config/platforms.ts */
  platformId: string
  /** Clean name for display, e.g. "LinkedIn" */
  platformName: string
  /** <title> tag content */
  title: string
  /** Meta description */
  description: string
  /** H1 displayed on the page */
  h1: string
  /** Subheading displayed under the H1 */
  heroSubheading: string
  /** Multi-sentence descriptive introduction */
  introText: string
  /** Targeted audience for this platform */
  audienceDescription: string
  /** Formatting tip specific to the platform */
  formattingTip: string
  /** Contrast details of platform-optimized vs lazy cross-posts */
  postMakerVsGeneric: {
    platformSpecific: string
    genericCrossPost: string
    explanation: string
  }
  /** Unique platform features provided by PostMaker */
  features: PlatformFeature[]
  /** FAQs for visible accordion and FAQPage schema injection */
  faqs: PlatformFAQ[]
  /** Tailored CTA button text */
  ctaText: string
  ogImage?: string
}

export const platformPages: PlatformPageEntry[] = [
  {
    "slug": "linkedin",
    "platformId": "linkedin",
    "platformName": "LinkedIn",
    "title": "Free AI LinkedIn Post Generator & Formatter | PostMaker",
    "description": "Generate properly formatted, high-engagement LinkedIn posts with a structured hook-story-takeaway layout. Elevate your professional personal brand.",
    "h1": "AI LinkedIn Post Generator",
    "heroSubheading": "Format professional, story-driven posts that build connections and drive B2B engagement.",
    "introText": "LinkedIn is the premier network for professional thought leadership, but writing there requires a balance of story-telling and clean typography. Walls of text are ignored. PostMaker shapes your ideas into standard hook-story-takeaway layouts with proper white space, bullet points, and high-context hashtags to ensure your personal brand stands out in the feed.",
    "audienceDescription": "Founders, executives, product managers, and B2B marketers looking to build professional authority.",
    "formattingTip": "Start with a single-line hook, separate paragraphs with double line-breaks, keep paragraphs under three lines, use bullet lists for scannability, and restrict hashtags to 3-5 relevant ones at the bottom.",
    "postMakerVsGeneric": {
      "platformSpecific": "An engaging story-led post structured with a hook, narrative progression, clear takeaway bullets, and 3 clean hashtags at the end.",
      "genericCrossPost": "A raw link preview or a short sentence with irrelevant hashtags copied from Twitter.",
      "explanation": "LinkedIn's algorithm demotes lazy link dumps and promotes text posts that retain user attention through readable formatting and professional storytelling."
    },
    "features": [
      {
        "title": "Hook-Story-Takeaway Structure",
        "description": "Builds authority by structuring your professional lessons and insights logically."
      },
      {
        "title": "Whitespace Optimization",
        "description": "Injects readable line breaks so readers stay on your post without eye strain."
      },
      {
        "title": "B2B Tone Adaptation",
        "description": "Maintains a professional, humble, yet authoritative voice that resonates with peers."
      }
    ],
    "faqs": [
      {
        "question": "How long should a LinkedIn post be?",
        "answer": "While the character limit is 3,000, the highest-performing posts range between 1,000 to 2,000 characters, formatted with abundant white space."
      },
      {
        "question": "Where should I place hashtags on LinkedIn?",
        "answer": "Always place them in a clean block at the very bottom of the post. Mixing them inline breaks readability and reduces user engagement."
      }
    ],
    "ctaText": "Generate LinkedIn Post"
  },
  {
    "slug": "instagram",
    "platformId": "instagram",
    "platformName": "Instagram",
    "title": "AI Instagram Caption Generator & Formatter | PostMaker",
    "description": "Create scroll-stopping Instagram captions with natural emoji placement, clean line breaks, and optimized hashtag blocks to boost your organic reach.",
    "h1": "AI Instagram Caption Generator",
    "heroSubheading": "Write engaging captions with clean spacing, active hooks, and smart hashtag groups.",
    "introText": "Instagram is a visual-first platform, but the caption is what drives saves, comments, and shares. Captions with messy layouts or blocks of hashtags mixed in the text hurt engagement. PostMaker formats clean, readable spacing, integrates context-aware emojis, and appends a clean hashtag block separated from your main message to maximize your reach and visibility.",
    "audienceDescription": "Content creators, influencer marketers, brand managers, and ecommerce shops looking to grow their following.",
    "formattingTip": "Put the hook in the first 125 characters (before the \"more\" button), use clean line breaks (no periods for spacing needed), use emojis to break up sections, and place hashtags at the very end.",
    "postMakerVsGeneric": {
      "platformSpecific": "A structured caption with an immediate hook, bulleted details, clean space, and a separate hashtag block.",
      "genericCrossPost": "A block of unformatted text with no line breaks and hashtags scattered everywhere.",
      "explanation": "Instagram hides captions after two lines. PostMaker ensures your hook is fully visible and the rest of the text is structured for clean reading."
    },
    "features": [
      {
        "title": "Instant Hook Placement",
        "description": "Puts the most engaging hook line at the very front to capture scrolling users."
      },
      {
        "title": "Perfect Caption Line Breaks",
        "description": "Formats your caption with clean visual spaces without requiring arbitrary symbol dividers."
      },
      {
        "title": "Contextual Emoji Layout",
        "description": "Adds brand-aligned, modern emojis naturally to drive readability and interaction."
      }
    ],
    "faqs": [
      {
        "question": "Do Instagram captions affect search SEO?",
        "answer": "Yes! Instagram uses caption keywords for search results. PostMaker naturally weaves primary topic keywords into your captions to help you rank in search."
      },
      {
        "question": "How many hashtags should I include?",
        "answer": "While the limit is 30, highly engaged captions usually perform best with 5 to 15 targeted, relevant hashtags placed at the bottom."
      }
    ],
    "ctaText": "Write Instagram Caption"
  },
  {
    "slug": "twitter",
    "platformId": "twitter",
    "platformName": "X / Twitter",
    "title": "AI Twitter (X) Tweet & Thread Generator | PostMaker",
    "description": "Write high-impact tweets and viral threads optimized for the X / Twitter algorithm. Boost impressions, bookmarks, and retweets.",
    "h1": "AI X / Twitter Post Generator",
    "heroSubheading": "Craft punchy, high-signal tweets and structured threads that hook readers and go viral.",
    "introText": "X (formerly Twitter) is fast-paced and demands maximum signal in minimum characters. Standard marketing copy gets scrolled past. PostMaker compresses your ideas into punchy, high-impact tweets under the 280-character limit, or structures multi-part threads with high-converting hook setups to maximize replies, bookmarks, and retweets.",
    "audienceDescription": "Tech founders, creators, journalists, and brand strategists looking to grow an active audience.",
    "formattingTip": "Open with an interesting statistic or polarizing question, keep the first line under 100 characters, avoid heavy emoji usage, and end threads with a clear call-to-action.",
    "postMakerVsGeneric": {
      "platformSpecific": "A clean, high-signal tweet presenting a single key insight, followed by an optimized thread link if necessary.",
      "genericCrossPost": "A long paragraph copied from a blog post that gets cut off or looks awkward in a tweet box.",
      "explanation": "X rewards brevity and conversation. PostMaker outputs single-concept ideas that naturally invite replies, bookmarks, and thread clicks."
    },
    "features": [
      {
        "title": "Signal-to-Noise Compression",
        "description": "Removes filler words to write concise, impactful tweets under the character limit."
      },
      {
        "title": "Thread Hook Formulation",
        "description": "Structures the opening tweet of threads to promise high value, forcing users to click and read."
      },
      {
        "title": "Algorithm-Friendly Layout",
        "description": "Avoids external links in main tweets when possible to ensure maximum reach."
      }
    ],
    "faqs": [
      {
        "question": "What length is best for a tweet on X?",
        "answer": "Even with premium long-form tweets, short posts (between 100 and 200 characters) generate the highest click-through and reply rates."
      },
      {
        "question": "Should I use hashtags on X / Twitter?",
        "answer": "Keep them to a minimum (1 or 2 at most). Flooding tweets with hashtags reduces engagement and looks spammy to the current algorithm."
      }
    ],
    "ctaText": "Write Tweet / Thread"
  },
  {
    "slug": "tiktok",
    "platformId": "tiktok",
    "platformName": "TikTok",
    "title": "AI TikTok Caption & Video Script Generator | PostMaker",
    "description": "Generate high-hook TikTok captions, trending hashtags, and video script outlines. Optimize your content for the TikTok FYP search algorithm.",
    "h1": "AI TikTok Video Copy Writer",
    "heroSubheading": "Draft attention-grabbing captions and quick video outlines optimized for viral reach.",
    "introText": "TikTok is driven by video hooks and keywords. The caption is crucial for TikTok SEO, helping the algorithm categorize your video for the FYP (For You Page) search engine. PostMaker creates short, high-energy captions with highly relevant, high-traffic hashtags, along with quick visual hooks that keep viewers watching past the critical 3-second mark.",
    "audienceDescription": "Creators, video editors, and brands seeking organic reach on mobile video feeds.",
    "formattingTip": "Include your main target keyword in the first sentence, keep captions short, use popular tag clusters, and write video title cards that immediately establish the benefit.",
    "postMakerVsGeneric": {
      "platformSpecific": "A punchy, interactive caption that asks a question to drive comments, accompanied by trending keyword tags.",
      "genericCrossPost": "A dry, formal paragraph with no energy or visual cues.",
      "explanation": "TikTok comments drive virality. PostMaker structures captions to ask engaging questions that encourage immediate viewer replies."
    },
    "features": [
      {
        "title": "TikTok SEO Keyword Targeter",
        "description": "Naturally weaves searchable terms into the caption to help your video appear in search results."
      },
      {
        "title": "Engagement Prompters",
        "description": "Drafts conversational, polarizing, or open-ended prompts to boost comment velocity."
      },
      {
        "title": "Hook-Oriented Structure",
        "description": "Optimized for high-retention video formats to stop users from swiping away."
      }
    ],
    "faqs": [
      {
        "question": "How long should a TikTok caption be?",
        "answer": "Keep it brief (under 150 characters) so it doesn't block the video screen, but make sure to include your primary search keywords."
      },
      {
        "question": "How does TikTok search SEO work?",
        "answer": "TikTok ranks videos based on keywords in the video caption, the video sound, and the text on screen. PostMaker optimizes caption text for these search bots."
      }
    ],
    "ctaText": "Write TikTok Copy"
  },
  {
    "slug": "facebook",
    "platformId": "facebook",
    "platformName": "Facebook",
    "title": "AI Facebook Post & Ad Copy Generator | PostMaker",
    "description": "Write engaging Facebook posts and high-converting ad copy. Build community, increase post shares, and drive organic link clicks.",
    "h1": "AI Facebook Post Creator",
    "heroSubheading": "Write conversational posts and social ad copy that spark discussions and drive shares.",
    "introText": "Facebook groups and pages reward community discussions and family-style sharing. Corporate jargon or dry links get buried. PostMaker optimizes your ideas into warm, conversational updates that prompt comments, invite reactions, and structure links to maintain high organic reach and engagement on both profiles and business pages.",
    "audienceDescription": "Local businesses, community managers, and social media marketers building brand loyalty.",
    "formattingTip": "Open with a friendly question, break text into short readable paragraphs, keep calls-to-action conversational, and limit hashtags to 1-2 relevant tags.",
    "postMakerVsGeneric": {
      "platformSpecific": "A friendly, community-first update ending with an open question, formatted with clean spacing.",
      "genericCrossPost": "A copy-paste of a long, dry press release with a wall of text.",
      "explanation": "Facebook's algorithm ranks posts higher when friends and family interact in the comment section. PostMaker builds comments in mind."
    },
    "features": [
      {
        "title": "Discussion Starters",
        "description": "Designs prompts that encourage followers to share their own experiences in the comments."
      },
      {
        "title": "Clean Link Formatting",
        "description": "Optimizes paragraph placement around external links to maximize click-through rate."
      },
      {
        "title": "Friendly Brand Tone",
        "description": "Maintains an approachable, helpful tone that builds community trust."
      }
    ],
    "faqs": [
      {
        "question": "Do hashtags work on Facebook?",
        "answer": "Yes, but sparingly. 1 or 2 relevant hashtags can help discoverability in groups and search, but more than that reduces engagement."
      },
      {
        "question": "What is the best post format for Facebook engagement?",
        "answer": "Posts that ask an open-ended question or share a short, authentic story with clean paragraph breaks generate the highest reach."
      }
    ],
    "ctaText": "Write Facebook Post"
  },
  {
    "slug": "pinterest",
    "platformId": "pinterest",
    "platformName": "Pinterest",
    "title": "AI Pinterest Pin Description & Board Optimizer | PostMaker",
    "description": "Generate keyword-rich Pinterest Pin descriptions and board titles. Drive continuous, long-term referral traffic to your blog or shop.",
    "h1": "AI Pinterest Pin Writer",
    "heroSubheading": "Draft search-optimized Pin descriptions that drive clicks, saves, and long-term website traffic.",
    "introText": "Pinterest is a visual search engine, not a social feed. Pins can drive traffic to your website for months or even years, but only if they are properly indexed. PostMaker generates descriptive, keyword-rich Pin descriptions that naturally incorporate target search queries while providing clear call-to-actions to encourage users to click through to your link.",
    "audienceDescription": "Bloggers, Shopify stores, recipe creators, and design brands looking for referral traffic.",
    "formattingTip": "Put the primary keyword in the first sentence, write descriptive text explaining the benefit, use up to 4 relevant tags, and include a clear call-to-action.",
    "postMakerVsGeneric": {
      "platformSpecific": "A keyword-dense description that reads naturally and includes a clear, compelling reason to click the link.",
      "genericCrossPost": "A short, one-word caption like \"Nice!\" or a generic title with no search value.",
      "explanation": "Pinterest rely on text descriptions to understand and index images. PostMaker provides the necessary context for search bots."
    },
    "features": [
      {
        "title": "Visual SEO Targeter",
        "description": "Weaves highly searched visual keywords naturally into descriptions to rank in Pinterest Search."
      },
      {
        "title": "Click-Through Prompters",
        "description": "Includes a clear, compelling reason for users to click the Pin to visit your blog or store."
      },
      {
        "title": "Board Alignment SEO",
        "description": "Optimizes copy to match board categories, improving categorization and indexing."
      }
    ],
    "faqs": [
      {
        "question": "How long should a Pin description be?",
        "answer": "While the limit is 500 characters, search algorithms prioritize the first 100 to 200 characters. Keep your main keywords up front."
      },
      {
        "question": "Should I use hashtags on Pinterest?",
        "answer": "Pinterest has moved away from hashtags in search. Focus instead on descriptive keywords and natural phrasing in the caption."
      }
    ],
    "ctaText": "Write Pin Description"
  },
  {
    "slug": "youtube",
    "platformId": "youtube",
    "platformName": "YouTube",
    "title": "AI YouTube Video Description & Outline Generator | PostMaker",
    "description": "Write search-optimized YouTube video descriptions, video tags, and chapters to boost your CTR and rank higher in search results.",
    "h1": "AI YouTube Video Optimizer",
    "heroSubheading": "Generate keyword-dense descriptions, video chapters, and script outlines that rank.",
    "introText": "YouTube is the second largest search engine in the world. Uploading videos without descriptions, metadata, or timestamps prevents you from ranking in search and suggestion algorithms. PostMaker generates detailed, search-friendly video descriptions, constructs timestamps/chapters, and structures social links to maximize subscriber growth and traffic.",
    "audienceDescription": "YouTubers, video creators, video editors, and brands using video marketing.",
    "formattingTip": "Put your primary keyword in the first 2 lines, include timestamps for video navigation, add links to your website, and list related video playlists.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detailed video description structured with a summary, timestamps, social links, and targeted keyword tags.",
      "genericCrossPost": "A blank description box or a simple link with no context.",
      "explanation": "YouTube's search bot reads video descriptions to index and recommend content. PostMaker ensures you never miss a search opportunity."
    },
    "features": [
      {
        "title": "Timestamp & Chapter Builders",
        "description": "Helps structure video chapters to satisfy search engines and improve user watch times."
      },
      {
        "title": "Above-the-Fold Optimization",
        "description": "Ensures the first 200 characters are highly click-worthy before the \"Show More\" line."
      },
      {
        "title": "Video SEO Meta Tags",
        "description": "Suggests high-relevance video tags and search keywords to improve recommendations."
      }
    ],
    "faqs": [
      {
        "question": "Does the YouTube description affect views?",
        "answer": "Absolutely. A detailed, keyword-rich description helps YouTube understand your video, leading to higher rankings and more recommendations."
      },
      {
        "question": "How many keywords should I target in the description?",
        "answer": "Target 1 primary keyword in the title and first paragraph, and 3-5 secondary keywords throughout the rest of the description."
      }
    ],
    "ctaText": "Optimize Video Description"
  },
  {
    "slug": "threads",
    "platformId": "threads",
    "platformName": "Threads",
    "title": "AI Threads Post & Conversation Generator | PostMaker",
    "description": "Create engaging, text-first posts optimized for Meta's Threads algorithm. Grow your followers with conversational, high-engagement updates.",
    "h1": "AI Threads Post Generator",
    "heroSubheading": "Draft conversational, text-first posts that spark immediate replies and grow your reach.",
    "introText": "Threads is a text-first, community-driven social feed built by Meta. It prioritizes authentic, personal updates that read like messaging a smart colleague. Rigid marketing copy, external links, and walls of hashtags fail to perform. PostMaker crafts highly conversational, human posts optimized to generate replies and rank well in the Threads recommendation feed.",
    "audienceDescription": "Creators, personal brands, and social managers looking to establish a presence on Threads.",
    "formattingTip": "Keep it casual and text-first, ask questions that require short answers, avoid hashtags completely, and respond quickly to replies.",
    "postMakerVsGeneric": {
      "platformSpecific": "A casual, personal observation or thought that reads like a real-time update and invites replies.",
      "genericCrossPost": "A corporate press release with a link and 10 hashtags copied from Instagram.",
      "explanation": "Threads rewards authentic conversations. PostMaker ensures your copy feels native and conversational, fitting the platform's culture."
    },
    "features": [
      {
        "title": "Conversational Tone Tuning",
        "description": "Writes casual, text-first posts that read like a real human update, not a marketing team."
      },
      {
        "title": "Reply-Driven Hooks",
        "description": "Structures statements to naturally invite replies, boosting your reach in the feed."
      },
      {
        "title": "No-Hashtag Clean Layout",
        "description": "Keeps posts clean and readable by completely avoiding hashtags, aligning with Threads culture."
      }
    ],
    "faqs": [
      {
        "question": "Does the Threads algorithm favor link posts?",
        "answer": "No. The Threads algorithm prioritizes text-first posts that spark discussions. PostMaker focuses on formatting text updates that keep users talking."
      },
      {
        "question": "Can I add hashtags on Threads?",
        "answer": "Threads uses tags rather than traditional hashtags. It is best to use clean text updates and add one single tag if necessary, but keep the copy clean."
      }
    ],
    "ctaText": "Write Threads Post"
  },
  {
    "slug": "bluesky",
    "platformId": "bluesky",
    "platformName": "Bluesky",
    "title": "AI Bluesky Caption & Short Post Writer | PostMaker",
    "description": "Craft high-impact, short-form posts and captions for Bluesky. Drive replies, retweets, and follower growth with clean copy.",
    "h1": "AI Bluesky Post Creator",
    "heroSubheading": "Generate punchy, high-engagement updates and short posts optimized for Bluesky.",
    "introText": "Short-form feeds require writing that is concise, impactful, and immediately conversational. PostMaker translates your core ideas into punchy, scroll-stopping updates that fit within the platform limitations of Bluesky, boosting impressions, likes, and shares.",
    "audienceDescription": "Content creators, personal brands, and social media managers posting updates on the go.",
    "formattingTip": "Make the first line punchy, use spacing to break up phrases, keep the tone casual, and place tags neatly at the end if applicable.",
    "postMakerVsGeneric": {
      "platformSpecific": "A short, high-signal observation or question that reads naturally and invites immediate replies.",
      "genericCrossPost": "A copy-paste of a long blog paragraph that gets cut off or looks too formal for a quick feed.",
      "explanation": "Bluesky users browse quickly. Short, conversational thoughts generate far more interaction than generic copy."
    },
    "features": [
      {
        "title": "Concise Compression",
        "description": "Compresses ideas into high-signal sentences that deliver maximum impact in minimal characters."
      },
      {
        "title": "Interactive Prompters",
        "description": "Finishes updates with natural prompts or questions to stimulate the comment section."
      },
      {
        "title": "Native Feed Styling",
        "description": "Outputs formatting, emojis, and hashtags that match the exact visual style and limits of Bluesky."
      }
    ],
    "faqs": [
      {
        "question": "What is the character limit for Bluesky?",
        "answer": "PostMaker automatically respects Bluesky's exact character and media limit rules so your post is always ready to publish."
      },
      {
        "question": "How do I get more reach on Bluesky?",
        "answer": "Keep posts short, spark comments with open-ended questions, and write posts that invite users to bookmark or share."
      }
    ],
    "ctaText": "Generate Bluesky Post"
  },
  {
    "slug": "mastodon",
    "platformId": "mastodon",
    "platformName": "Mastodon",
    "title": "AI Mastodon Caption & Short Post Writer | PostMaker",
    "description": "Craft high-impact, short-form posts and captions for Mastodon. Drive replies, retweets, and follower growth with clean copy.",
    "h1": "AI Mastodon Post Creator",
    "heroSubheading": "Generate punchy, high-engagement updates and short posts optimized for Mastodon.",
    "introText": "Short-form feeds require writing that is concise, impactful, and immediately conversational. PostMaker translates your core ideas into punchy, scroll-stopping updates that fit within the platform limitations of Mastodon, boosting impressions, likes, and shares.",
    "audienceDescription": "Content creators, personal brands, and social media managers posting updates on the go.",
    "formattingTip": "Make the first line punchy, use spacing to break up phrases, keep the tone casual, and place tags neatly at the end if applicable.",
    "postMakerVsGeneric": {
      "platformSpecific": "A short, high-signal observation or question that reads naturally and invites immediate replies.",
      "genericCrossPost": "A copy-paste of a long blog paragraph that gets cut off or looks too formal for a quick feed.",
      "explanation": "Mastodon users browse quickly. Short, conversational thoughts generate far more interaction than generic copy."
    },
    "features": [
      {
        "title": "Concise Compression",
        "description": "Compresses ideas into high-signal sentences that deliver maximum impact in minimal characters."
      },
      {
        "title": "Interactive Prompters",
        "description": "Finishes updates with natural prompts or questions to stimulate the comment section."
      },
      {
        "title": "Native Feed Styling",
        "description": "Outputs formatting, emojis, and hashtags that match the exact visual style and limits of Mastodon."
      }
    ],
    "faqs": [
      {
        "question": "What is the character limit for Mastodon?",
        "answer": "PostMaker automatically respects Mastodon's exact character and media limit rules so your post is always ready to publish."
      },
      {
        "question": "How do I get more reach on Mastodon?",
        "answer": "Keep posts short, spark comments with open-ended questions, and write posts that invite users to bookmark or share."
      }
    ],
    "ctaText": "Generate Mastodon Post"
  },
  {
    "slug": "snapchat",
    "platformId": "snapchat",
    "platformName": "Snapchat",
    "title": "AI Snapchat Caption & Short Post Writer | PostMaker",
    "description": "Craft high-impact, short-form posts and captions for Snapchat. Drive replies, retweets, and follower growth with clean copy.",
    "h1": "AI Snapchat Post Creator",
    "heroSubheading": "Generate punchy, high-engagement updates and short posts optimized for Snapchat.",
    "introText": "Short-form feeds require writing that is concise, impactful, and immediately conversational. PostMaker translates your core ideas into punchy, scroll-stopping updates that fit within the platform limitations of Snapchat, boosting impressions, likes, and shares.",
    "audienceDescription": "Content creators, personal brands, and social media managers posting updates on the go.",
    "formattingTip": "Make the first line punchy, use spacing to break up phrases, keep the tone casual, and place tags neatly at the end if applicable.",
    "postMakerVsGeneric": {
      "platformSpecific": "A short, high-signal observation or question that reads naturally and invites immediate replies.",
      "genericCrossPost": "A copy-paste of a long blog paragraph that gets cut off or looks too formal for a quick feed.",
      "explanation": "Snapchat users browse quickly. Short, conversational thoughts generate far more interaction than generic copy."
    },
    "features": [
      {
        "title": "Concise Compression",
        "description": "Compresses ideas into high-signal sentences that deliver maximum impact in minimal characters."
      },
      {
        "title": "Interactive Prompters",
        "description": "Finishes updates with natural prompts or questions to stimulate the comment section."
      },
      {
        "title": "Native Feed Styling",
        "description": "Outputs formatting, emojis, and hashtags that match the exact visual style and limits of Snapchat."
      }
    ],
    "faqs": [
      {
        "question": "What is the character limit for Snapchat?",
        "answer": "PostMaker automatically respects Snapchat's exact character and media limit rules so your post is always ready to publish."
      },
      {
        "question": "How do I get more reach on Snapchat?",
        "answer": "Keep posts short, spark comments with open-ended questions, and write posts that invite users to bookmark or share."
      }
    ],
    "ctaText": "Generate Snapchat Post"
  },
  {
    "slug": "reddit",
    "platformId": "reddit",
    "platformName": "Reddit",
    "title": "AI Reddit Post & Answer Formatter | PostMaker",
    "description": "Format engaging posts, sub-community threads, and detailed answers for Reddit. Speak with authenticity and drive upvotes.",
    "h1": "AI Reddit Content Formatter",
    "heroSubheading": "Write detailed, community-centric posts and answers that gain upvotes and spark discussions.",
    "introText": "Community forums like Reddit reject standard marketing copy immediately. To get upvotes and visibility, you must share genuine, helpful, and highly detailed answers. PostMaker formats your copy to fit the specific culture of Reddit, prioritizing authentic story-telling, formatting markdown lists cleanly, and structuring questions to invite discussion.",
    "audienceDescription": "Niche marketers, community builders, and experts sharing knowledge in specific forums.",
    "formattingTip": "Be helpful first, format with bold headers and lists for scannability, share personal experiences, and avoid direct sales pitches.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detailed, helpful answer sharing step-by-step guides with clean formatting, mentioning your product only if relevant.",
      "genericCrossPost": "A short \"Buy my product here\" spam post with a direct affiliate link.",
      "explanation": "Reddit algorithms and moderators block spam. PostMaker builds reputation-friendly, helpful posts that drive organic upvotes."
    },
    "features": [
      {
        "title": "Sub-Community Adaptability",
        "description": "Adjusts the copy tone to match the specific rules and culture of different community forums."
      },
      {
        "title": "Markdown Spacing",
        "description": "Applies clean bold text, headers, and bullet points to make long answers highly readable."
      },
      {
        "title": "Authenticity Filter",
        "description": "Rewrites promotional claims into honest, value-first sharing that drives upvotes."
      }
    ],
    "faqs": [
      {
        "question": "How do I drive traffic from Reddit without getting banned?",
        "answer": "Always focus on answering the question completely and helping the reader. Only link to your resource if it directly adds deep value to the discussion."
      },
      {
        "question": "Does formatting affect upvotes?",
        "answer": "Yes! Properly spaced posts with bold headers, bullet lists, and clear paragraphs get read more and receive significantly more upvotes."
      }
    ],
    "ctaText": "Generate Reddit Post"
  },
  {
    "slug": "hackernews",
    "platformId": "hackernews",
    "platformName": "Hacker News",
    "title": "Free AI Hacker News Post & Launch Copy Generator | PostMaker",
    "description": "Write high-converting launch copy, technical updates, and posts for Hacker News. Speak directly to developers, founders, and early adopters.",
    "h1": "AI Hacker News Post Generator",
    "heroSubheading": "Draft clear, high-value launch copy and technical updates for the Hacker News community.",
    "introText": "The Hacker News community values technical depth, transparency, and authenticity. Marketing hype, fluff, and generic buzzwords fail completely on this platform. PostMaker structures your copy to present clear features, stack choices, metrics, or repository links, ensuring your launch or update stands out to fellow developers and makers.",
    "audienceDescription": "Founders, software developers, technical product managers, and builders launching products.",
    "formattingTip": "Lead with real features or data, format lists clearly, provide links for deep dives, and avoid hard sales copy.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detail-oriented update sharing key features, stack decisions, performance data, and a repository link.",
      "genericCrossPost": "A generic \"So excited to announce our tool!\" marketing blast with 15 tags and zero details.",
      "explanation": "Builders scroll past vague claims. Sharing exact specs and metrics builds trust and increases CTR on Hacker News."
    },
    "features": [
      {
        "title": "Authentic Tech Tone",
        "description": "Communicates in a clean, professional developer-friendly voice, avoiding typical corporate marketing fluff."
      },
      {
        "title": "Product Launch Formatting",
        "description": "Structures product updates, features, and links into high-scannability blocks ideal for product launches."
      },
      {
        "title": "Clear Value Hooks",
        "description": "Highlights performance specs, repo statistics, or Stack details in the opening sentences to hold attention."
      }
    ],
    "faqs": [
      {
        "question": "How should I write a launch post for Hacker News?",
        "answer": "Focus on the problem you are solving, detail your stack and how it works, share real numbers, and invite constructive feedback from the community."
      },
      {
        "question": "Does PostMaker format code snippets?",
        "answer": "Yes. PostMaker structures and spaces your technical descriptions, making them clean and readable for platforms like Hacker News."
      }
    ],
    "ctaText": "Generate Hacker News Post"
  },
  {
    "slug": "producthunt",
    "platformId": "producthunt",
    "platformName": "Product Hunt",
    "title": "Free AI Product Hunt Post & Launch Copy Generator | PostMaker",
    "description": "Write high-converting launch copy, technical updates, and posts for Product Hunt. Speak directly to developers, founders, and early adopters.",
    "h1": "AI Product Hunt Post Generator",
    "heroSubheading": "Draft clear, high-value launch copy and technical updates for the Product Hunt community.",
    "introText": "The Product Hunt community values technical depth, transparency, and authenticity. Marketing hype, fluff, and generic buzzwords fail completely on this platform. PostMaker structures your copy to present clear features, stack choices, metrics, or repository links, ensuring your launch or update stands out to fellow developers and makers.",
    "audienceDescription": "Founders, software developers, technical product managers, and builders launching products.",
    "formattingTip": "Lead with real features or data, format lists clearly, provide links for deep dives, and avoid hard sales copy.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detail-oriented update sharing key features, stack decisions, performance data, and a repository link.",
      "genericCrossPost": "A generic \"So excited to announce our tool!\" marketing blast with 15 tags and zero details.",
      "explanation": "Builders scroll past vague claims. Sharing exact specs and metrics builds trust and increases CTR on Product Hunt."
    },
    "features": [
      {
        "title": "Authentic Tech Tone",
        "description": "Communicates in a clean, professional developer-friendly voice, avoiding typical corporate marketing fluff."
      },
      {
        "title": "Product Launch Formatting",
        "description": "Structures product updates, features, and links into high-scannability blocks ideal for product launches."
      },
      {
        "title": "Clear Value Hooks",
        "description": "Highlights performance specs, repo statistics, or Stack details in the opening sentences to hold attention."
      }
    ],
    "faqs": [
      {
        "question": "How should I write a launch post for Product Hunt?",
        "answer": "Focus on the problem you are solving, detail your stack and how it works, share real numbers, and invite constructive feedback from the community."
      },
      {
        "question": "Does PostMaker format code snippets?",
        "answer": "Yes. PostMaker structures and spaces your technical descriptions, making them clean and readable for platforms like Product Hunt."
      }
    ],
    "ctaText": "Generate Product Hunt Post"
  },
  {
    "slug": "indiehackers",
    "platformId": "indiehackers",
    "platformName": "Indie Hackers",
    "title": "Free AI Indie Hackers Post & Launch Copy Generator | PostMaker",
    "description": "Write high-converting launch copy, technical updates, and posts for Indie Hackers. Speak directly to developers, founders, and early adopters.",
    "h1": "AI Indie Hackers Post Generator",
    "heroSubheading": "Draft clear, high-value launch copy and technical updates for the Indie Hackers community.",
    "introText": "The Indie Hackers community values technical depth, transparency, and authenticity. Marketing hype, fluff, and generic buzzwords fail completely on this platform. PostMaker structures your copy to present clear features, stack choices, metrics, or repository links, ensuring your launch or update stands out to fellow developers and makers.",
    "audienceDescription": "Founders, software developers, technical product managers, and builders launching products.",
    "formattingTip": "Lead with real features or data, format lists clearly, provide links for deep dives, and avoid hard sales copy.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detail-oriented update sharing key features, stack decisions, performance data, and a repository link.",
      "genericCrossPost": "A generic \"So excited to announce our tool!\" marketing blast with 15 tags and zero details.",
      "explanation": "Builders scroll past vague claims. Sharing exact specs and metrics builds trust and increases CTR on Indie Hackers."
    },
    "features": [
      {
        "title": "Authentic Tech Tone",
        "description": "Communicates in a clean, professional developer-friendly voice, avoiding typical corporate marketing fluff."
      },
      {
        "title": "Product Launch Formatting",
        "description": "Structures product updates, features, and links into high-scannability blocks ideal for product launches."
      },
      {
        "title": "Clear Value Hooks",
        "description": "Highlights performance specs, repo statistics, or Stack details in the opening sentences to hold attention."
      }
    ],
    "faqs": [
      {
        "question": "How should I write a launch post for Indie Hackers?",
        "answer": "Focus on the problem you are solving, detail your stack and how it works, share real numbers, and invite constructive feedback from the community."
      },
      {
        "question": "Does PostMaker format code snippets?",
        "answer": "Yes. PostMaker structures and spaces your technical descriptions, making them clean and readable for platforms like Indie Hackers."
      }
    ],
    "ctaText": "Generate Indie Hackers Post"
  },
  {
    "slug": "betalist",
    "platformId": "betalist",
    "platformName": "BetaList",
    "title": "Free AI BetaList Post & Launch Copy Generator | PostMaker",
    "description": "Write high-converting launch copy, technical updates, and posts for BetaList. Speak directly to developers, founders, and early adopters.",
    "h1": "AI BetaList Post Generator",
    "heroSubheading": "Draft clear, high-value launch copy and technical updates for the BetaList community.",
    "introText": "The BetaList community values technical depth, transparency, and authenticity. Marketing hype, fluff, and generic buzzwords fail completely on this platform. PostMaker structures your copy to present clear features, stack choices, metrics, or repository links, ensuring your launch or update stands out to fellow developers and makers.",
    "audienceDescription": "Founders, software developers, technical product managers, and builders launching products.",
    "formattingTip": "Lead with real features or data, format lists clearly, provide links for deep dives, and avoid hard sales copy.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detail-oriented update sharing key features, stack decisions, performance data, and a repository link.",
      "genericCrossPost": "A generic \"So excited to announce our tool!\" marketing blast with 15 tags and zero details.",
      "explanation": "Builders scroll past vague claims. Sharing exact specs and metrics builds trust and increases CTR on BetaList."
    },
    "features": [
      {
        "title": "Authentic Tech Tone",
        "description": "Communicates in a clean, professional developer-friendly voice, avoiding typical corporate marketing fluff."
      },
      {
        "title": "Product Launch Formatting",
        "description": "Structures product updates, features, and links into high-scannability blocks ideal for product launches."
      },
      {
        "title": "Clear Value Hooks",
        "description": "Highlights performance specs, repo statistics, or Stack details in the opening sentences to hold attention."
      }
    ],
    "faqs": [
      {
        "question": "How should I write a launch post for BetaList?",
        "answer": "Focus on the problem you are solving, detail your stack and how it works, share real numbers, and invite constructive feedback from the community."
      },
      {
        "question": "Does PostMaker format code snippets?",
        "answer": "Yes. PostMaker structures and spaces your technical descriptions, making them clean and readable for platforms like BetaList."
      }
    ],
    "ctaText": "Generate BetaList Post"
  },
  {
    "slug": "discord",
    "platformId": "discord",
    "platformName": "Discord",
    "title": "AI Discord Post & Answer Formatter | PostMaker",
    "description": "Format engaging posts, sub-community threads, and detailed answers for Discord. Speak with authenticity and drive upvotes.",
    "h1": "AI Discord Content Formatter",
    "heroSubheading": "Write detailed, community-centric posts and answers that gain upvotes and spark discussions.",
    "introText": "Community forums like Discord reject standard marketing copy immediately. To get upvotes and visibility, you must share genuine, helpful, and highly detailed answers. PostMaker formats your copy to fit the specific culture of Discord, prioritizing authentic story-telling, formatting markdown lists cleanly, and structuring questions to invite discussion.",
    "audienceDescription": "Niche marketers, community builders, and experts sharing knowledge in specific forums.",
    "formattingTip": "Be helpful first, format with bold headers and lists for scannability, share personal experiences, and avoid direct sales pitches.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detailed, helpful answer sharing step-by-step guides with clean formatting, mentioning your product only if relevant.",
      "genericCrossPost": "A short \"Buy my product here\" spam post with a direct affiliate link.",
      "explanation": "Discord algorithms and moderators block spam. PostMaker builds reputation-friendly, helpful posts that drive organic upvotes."
    },
    "features": [
      {
        "title": "Sub-Community Adaptability",
        "description": "Adjusts the copy tone to match the specific rules and culture of different community forums."
      },
      {
        "title": "Markdown Spacing",
        "description": "Applies clean bold text, headers, and bullet points to make long answers highly readable."
      },
      {
        "title": "Authenticity Filter",
        "description": "Rewrites promotional claims into honest, value-first sharing that drives upvotes."
      }
    ],
    "faqs": [
      {
        "question": "How do I drive traffic from Discord without getting banned?",
        "answer": "Always focus on answering the question completely and helping the reader. Only link to your resource if it directly adds deep value to the discussion."
      },
      {
        "question": "Does formatting affect upvotes?",
        "answer": "Yes! Properly spaced posts with bold headers, bullet lists, and clear paragraphs get read more and receive significantly more upvotes."
      }
    ],
    "ctaText": "Generate Discord Post"
  },
  {
    "slug": "medium",
    "platformId": "medium",
    "platformName": "Medium",
    "title": "AI Medium Headline & Hook Generator | PostMaker",
    "description": "Generate engaging headlines, newsletter hooks, and article structures for Medium. Convert casual readers into subscribers.",
    "h1": "AI Medium Article Hook Writer",
    "heroSubheading": "Craft scroll-stopping titles and introduction hooks that double your Medium read rates.",
    "introText": "Writing on Medium requires capturing readers in the first two sentences and structuring content for deep reading. PostMaker generates high-CTR headlines, drafts compelling intro hooks, and maps readable outlines to ensure your publication grows its subscriber base.",
    "audienceDescription": "Writers, journalists, bloggers, and companies sharing newsletters or long-form thought leadership.",
    "formattingTip": "Use a curiosity-driven or metric-backed headline, establish the benefit in the first paragraph, and keep subheadings descriptive.",
    "postMakerVsGeneric": {
      "platformSpecific": "A curiosity-inducing headline combined with a clear, benefit-driven introductory paragraph.",
      "genericCrossPost": "A title like \"New Blog Post\" with no description or hook to encourage reading.",
      "explanation": "Long-form readers have high expectations. PostMaker helps you hook them instantly in the feed and lead them to the full article."
    },
    "features": [
      {
        "title": "High-CTR Headlining",
        "description": "Generates multiple headline options optimized to stand out in email inboxes and article feeds."
      },
      {
        "title": "Intro Hook Structuring",
        "description": "Crafts intro paragraphs that promise high value to keep readers scrolling down the page."
      },
      {
        "title": "Descriptive Outlining",
        "description": "Suggests structural outlines and subheadings to break up long essays into readable blocks."
      }
    ],
    "faqs": [
      {
        "question": "How can I grow my subscribers on Medium?",
        "answer": "Focus on delivering specific, actionable insights, write scroll-stopping headlines, and use clear newsletter signup prompts inside the text."
      },
      {
        "question": "What types of hooks work best for long-form?",
        "answer": "Hooks that share a surprising statistic, a personal realization, or a contrarian view generate the highest read rates."
      }
    ],
    "ctaText": "Generate Medium Post"
  },
  {
    "slug": "substack",
    "platformId": "substack",
    "platformName": "Substack",
    "title": "AI Substack Headline & Hook Generator | PostMaker",
    "description": "Generate engaging headlines, newsletter hooks, and article structures for Substack. Convert casual readers into subscribers.",
    "h1": "AI Substack Article Hook Writer",
    "heroSubheading": "Craft scroll-stopping titles and introduction hooks that double your Substack read rates.",
    "introText": "Writing on Substack requires capturing readers in the first two sentences and structuring content for deep reading. PostMaker generates high-CTR headlines, drafts compelling intro hooks, and maps readable outlines to ensure your publication grows its subscriber base.",
    "audienceDescription": "Writers, journalists, bloggers, and companies sharing newsletters or long-form thought leadership.",
    "formattingTip": "Use a curiosity-driven or metric-backed headline, establish the benefit in the first paragraph, and keep subheadings descriptive.",
    "postMakerVsGeneric": {
      "platformSpecific": "A curiosity-inducing headline combined with a clear, benefit-driven introductory paragraph.",
      "genericCrossPost": "A title like \"New Blog Post\" with no description or hook to encourage reading.",
      "explanation": "Long-form readers have high expectations. PostMaker helps you hook them instantly in the feed and lead them to the full article."
    },
    "features": [
      {
        "title": "High-CTR Headlining",
        "description": "Generates multiple headline options optimized to stand out in email inboxes and article feeds."
      },
      {
        "title": "Intro Hook Structuring",
        "description": "Crafts intro paragraphs that promise high value to keep readers scrolling down the page."
      },
      {
        "title": "Descriptive Outlining",
        "description": "Suggests structural outlines and subheadings to break up long essays into readable blocks."
      }
    ],
    "faqs": [
      {
        "question": "How can I grow my subscribers on Substack?",
        "answer": "Focus on delivering specific, actionable insights, write scroll-stopping headlines, and use clear newsletter signup prompts inside the text."
      },
      {
        "question": "What types of hooks work best for long-form?",
        "answer": "Hooks that share a surprising statistic, a personal realization, or a contrarian view generate the highest read rates."
      }
    ],
    "ctaText": "Generate Substack Post"
  },
  {
    "slug": "quora",
    "platformId": "quora",
    "platformName": "Quora",
    "title": "AI Quora Post & Answer Formatter | PostMaker",
    "description": "Format engaging posts, sub-community threads, and detailed answers for Quora. Speak with authenticity and drive upvotes.",
    "h1": "AI Quora Content Formatter",
    "heroSubheading": "Write detailed, community-centric posts and answers that gain upvotes and spark discussions.",
    "introText": "Community forums like Quora reject standard marketing copy immediately. To get upvotes and visibility, you must share genuine, helpful, and highly detailed answers. PostMaker formats your copy to fit the specific culture of Quora, prioritizing authentic story-telling, formatting markdown lists cleanly, and structuring questions to invite discussion.",
    "audienceDescription": "Niche marketers, community builders, and experts sharing knowledge in specific forums.",
    "formattingTip": "Be helpful first, format with bold headers and lists for scannability, share personal experiences, and avoid direct sales pitches.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detailed, helpful answer sharing step-by-step guides with clean formatting, mentioning your product only if relevant.",
      "genericCrossPost": "A short \"Buy my product here\" spam post with a direct affiliate link.",
      "explanation": "Quora algorithms and moderators block spam. PostMaker builds reputation-friendly, helpful posts that drive organic upvotes."
    },
    "features": [
      {
        "title": "Sub-Community Adaptability",
        "description": "Adjusts the copy tone to match the specific rules and culture of different community forums."
      },
      {
        "title": "Markdown Spacing",
        "description": "Applies clean bold text, headers, and bullet points to make long answers highly readable."
      },
      {
        "title": "Authenticity Filter",
        "description": "Rewrites promotional claims into honest, value-first sharing that drives upvotes."
      }
    ],
    "faqs": [
      {
        "question": "How do I drive traffic from Quora without getting banned?",
        "answer": "Always focus on answering the question completely and helping the reader. Only link to your resource if it directly adds deep value to the discussion."
      },
      {
        "question": "Does formatting affect upvotes?",
        "answer": "Yes! Properly spaced posts with bold headers, bullet lists, and clear paragraphs get read more and receive significantly more upvotes."
      }
    ],
    "ctaText": "Generate Quora Post"
  },
  {
    "slug": "devto",
    "platformId": "devto",
    "platformName": "dev.to",
    "title": "Free AI dev.to Post & Launch Copy Generator | PostMaker",
    "description": "Write high-converting launch copy, technical updates, and posts for dev.to. Speak directly to developers, founders, and early adopters.",
    "h1": "AI dev.to Post Generator",
    "heroSubheading": "Draft clear, high-value launch copy and technical updates for the dev.to community.",
    "introText": "The dev.to community values technical depth, transparency, and authenticity. Marketing hype, fluff, and generic buzzwords fail completely on this platform. PostMaker structures your copy to present clear features, stack choices, metrics, or repository links, ensuring your launch or update stands out to fellow developers and makers.",
    "audienceDescription": "Founders, software developers, technical product managers, and builders launching products.",
    "formattingTip": "Lead with real features or data, format lists clearly, provide links for deep dives, and avoid hard sales copy.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detail-oriented update sharing key features, stack decisions, performance data, and a repository link.",
      "genericCrossPost": "A generic \"So excited to announce our tool!\" marketing blast with 15 tags and zero details.",
      "explanation": "Builders scroll past vague claims. Sharing exact specs and metrics builds trust and increases CTR on dev.to."
    },
    "features": [
      {
        "title": "Authentic Tech Tone",
        "description": "Communicates in a clean, professional developer-friendly voice, avoiding typical corporate marketing fluff."
      },
      {
        "title": "Product Launch Formatting",
        "description": "Structures product updates, features, and links into high-scannability blocks ideal for product launches."
      },
      {
        "title": "Clear Value Hooks",
        "description": "Highlights performance specs, repo statistics, or Stack details in the opening sentences to hold attention."
      }
    ],
    "faqs": [
      {
        "question": "How should I write a launch post for dev.to?",
        "answer": "Focus on the problem you are solving, detail your stack and how it works, share real numbers, and invite constructive feedback from the community."
      },
      {
        "question": "Does PostMaker format code snippets?",
        "answer": "Yes. PostMaker structures and spaces your technical descriptions, making them clean and readable for platforms like dev.to."
      }
    ],
    "ctaText": "Generate dev.to Post"
  },
  {
    "slug": "hashnode",
    "platformId": "hashnode",
    "platformName": "Hashnode",
    "title": "Free AI Hashnode Post & Launch Copy Generator | PostMaker",
    "description": "Write high-converting launch copy, technical updates, and posts for Hashnode. Speak directly to developers, founders, and early adopters.",
    "h1": "AI Hashnode Post Generator",
    "heroSubheading": "Draft clear, high-value launch copy and technical updates for the Hashnode community.",
    "introText": "The Hashnode community values technical depth, transparency, and authenticity. Marketing hype, fluff, and generic buzzwords fail completely on this platform. PostMaker structures your copy to present clear features, stack choices, metrics, or repository links, ensuring your launch or update stands out to fellow developers and makers.",
    "audienceDescription": "Founders, software developers, technical product managers, and builders launching products.",
    "formattingTip": "Lead with real features or data, format lists clearly, provide links for deep dives, and avoid hard sales copy.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detail-oriented update sharing key features, stack decisions, performance data, and a repository link.",
      "genericCrossPost": "A generic \"So excited to announce our tool!\" marketing blast with 15 tags and zero details.",
      "explanation": "Builders scroll past vague claims. Sharing exact specs and metrics builds trust and increases CTR on Hashnode."
    },
    "features": [
      {
        "title": "Authentic Tech Tone",
        "description": "Communicates in a clean, professional developer-friendly voice, avoiding typical corporate marketing fluff."
      },
      {
        "title": "Product Launch Formatting",
        "description": "Structures product updates, features, and links into high-scannability blocks ideal for product launches."
      },
      {
        "title": "Clear Value Hooks",
        "description": "Highlights performance specs, repo statistics, or Stack details in the opening sentences to hold attention."
      }
    ],
    "faqs": [
      {
        "question": "How should I write a launch post for Hashnode?",
        "answer": "Focus on the problem you are solving, detail your stack and how it works, share real numbers, and invite constructive feedback from the community."
      },
      {
        "question": "Does PostMaker format code snippets?",
        "answer": "Yes. PostMaker structures and spaces your technical descriptions, making them clean and readable for platforms like Hashnode."
      }
    ],
    "ctaText": "Generate Hashnode Post"
  },
  {
    "slug": "github",
    "platformId": "github",
    "platformName": "GitHub",
    "title": "Free AI GitHub Post & Launch Copy Generator | PostMaker",
    "description": "Write high-converting launch copy, technical updates, and posts for GitHub. Speak directly to developers, founders, and early adopters.",
    "h1": "AI GitHub Post Generator",
    "heroSubheading": "Draft clear, high-value launch copy and technical updates for the GitHub community.",
    "introText": "The GitHub community values technical depth, transparency, and authenticity. Marketing hype, fluff, and generic buzzwords fail completely on this platform. PostMaker structures your copy to present clear features, stack choices, metrics, or repository links, ensuring your launch or update stands out to fellow developers and makers.",
    "audienceDescription": "Founders, software developers, technical product managers, and builders launching products.",
    "formattingTip": "Lead with real features or data, format lists clearly, provide links for deep dives, and avoid hard sales copy.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detail-oriented update sharing key features, stack decisions, performance data, and a repository link.",
      "genericCrossPost": "A generic \"So excited to announce our tool!\" marketing blast with 15 tags and zero details.",
      "explanation": "Builders scroll past vague claims. Sharing exact specs and metrics builds trust and increases CTR on GitHub."
    },
    "features": [
      {
        "title": "Authentic Tech Tone",
        "description": "Communicates in a clean, professional developer-friendly voice, avoiding typical corporate marketing fluff."
      },
      {
        "title": "Product Launch Formatting",
        "description": "Structures product updates, features, and links into high-scannability blocks ideal for product launches."
      },
      {
        "title": "Clear Value Hooks",
        "description": "Highlights performance specs, repo statistics, or Stack details in the opening sentences to hold attention."
      }
    ],
    "faqs": [
      {
        "question": "How should I write a launch post for GitHub?",
        "answer": "Focus on the problem you are solving, detail your stack and how it works, share real numbers, and invite constructive feedback from the community."
      },
      {
        "question": "Does PostMaker format code snippets?",
        "answer": "Yes. PostMaker structures and spaces your technical descriptions, making them clean and readable for platforms like GitHub."
      }
    ],
    "ctaText": "Generate GitHub Post"
  },
  {
    "slug": "stackoverflow",
    "platformId": "stackoverflow",
    "platformName": "Stack Overflow",
    "title": "Free AI Stack Overflow Post & Launch Copy Generator | PostMaker",
    "description": "Write high-converting launch copy, technical updates, and posts for Stack Overflow. Speak directly to developers, founders, and early adopters.",
    "h1": "AI Stack Overflow Post Generator",
    "heroSubheading": "Draft clear, high-value launch copy and technical updates for the Stack Overflow community.",
    "introText": "The Stack Overflow community values technical depth, transparency, and authenticity. Marketing hype, fluff, and generic buzzwords fail completely on this platform. PostMaker structures your copy to present clear features, stack choices, metrics, or repository links, ensuring your launch or update stands out to fellow developers and makers.",
    "audienceDescription": "Founders, software developers, technical product managers, and builders launching products.",
    "formattingTip": "Lead with real features or data, format lists clearly, provide links for deep dives, and avoid hard sales copy.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detail-oriented update sharing key features, stack decisions, performance data, and a repository link.",
      "genericCrossPost": "A generic \"So excited to announce our tool!\" marketing blast with 15 tags and zero details.",
      "explanation": "Builders scroll past vague claims. Sharing exact specs and metrics builds trust and increases CTR on Stack Overflow."
    },
    "features": [
      {
        "title": "Authentic Tech Tone",
        "description": "Communicates in a clean, professional developer-friendly voice, avoiding typical corporate marketing fluff."
      },
      {
        "title": "Product Launch Formatting",
        "description": "Structures product updates, features, and links into high-scannability blocks ideal for product launches."
      },
      {
        "title": "Clear Value Hooks",
        "description": "Highlights performance specs, repo statistics, or Stack details in the opening sentences to hold attention."
      }
    ],
    "faqs": [
      {
        "question": "How should I write a launch post for Stack Overflow?",
        "answer": "Focus on the problem you are solving, detail your stack and how it works, share real numbers, and invite constructive feedback from the community."
      },
      {
        "question": "Does PostMaker format code snippets?",
        "answer": "Yes. PostMaker structures and spaces your technical descriptions, making them clean and readable for platforms like Stack Overflow."
      }
    ],
    "ctaText": "Generate Stack Overflow Post"
  },
  {
    "slug": "youtubeshorts",
    "platformId": "youtubeshorts",
    "platformName": "YouTube Shorts",
    "title": "AI YouTube Shorts Script Outline & Video Description Writer | PostMaker",
    "description": "Write high-retention video hooks, script outlines, and descriptions for YouTube Shorts. Grow subscribers and video views.",
    "h1": "AI YouTube Shorts Script & Promo Writer",
    "heroSubheading": "Generate attention-grabbing video scripts, hooks, and descriptions designed to keep viewers watching.",
    "introText": "Video and audio platforms are driven by watch time and retention. If your video hook is slow or boring, viewers swipe away in 3 seconds. PostMaker drafts quick, high-retention video script outlines, hooks, titles, and descriptions for YouTube Shorts to maximize CTR and keep viewers watching.",
    "audienceDescription": "Video creators, podcasters, stream hosts, and video editors seeking viral growth.",
    "formattingTip": "State the payoff in the first 3 seconds, structure scripts into hook-value-cta, and keep descriptions keyword-rich for search.",
    "postMakerVsGeneric": {
      "platformSpecific": "A structured script outline starting with a strong visual hook, followed by 3 key points and a quick CTA.",
      "genericCrossPost": "A dry, wordy script read that sounds like a textbook outline.",
      "explanation": "Online video feeds require conversational, fast-paced language. PostMaker drafts outlines that sound natural and high-energy."
    },
    "features": [
      {
        "title": "3-Second Hook Optimizer",
        "description": "Creates powerful visual and verbal openings that stop users from scrolling past your video."
      },
      {
        "title": "Visual Cue Prompts",
        "description": "Includes script suggestions for overlay text and visual shifts to maintain high viewer retention."
      },
      {
        "title": "SEO Description Sync",
        "description": "Optimizes video captions and search terms to match algorithm category search queries."
      }
    ],
    "faqs": [
      {
        "question": "How do I write a script hook that stops the scroll?",
        "answer": "Start in the middle of the action, address a major pain point immediately, or show the end result first to create curiosity."
      },
      {
        "question": "What is the optimal script structure for short video?",
        "answer": "Use the Hook (0-3s) -> Core Value/Story (3-45s) -> Call to Action (45-60s) layout for maximum retention."
      }
    ],
    "ctaText": "Generate YouTube Shorts Post"
  },
  {
    "slug": "twitch",
    "platformId": "twitch",
    "platformName": "Twitch",
    "title": "AI Twitch Script Outline & Video Description Writer | PostMaker",
    "description": "Write high-retention video hooks, script outlines, and descriptions for Twitch. Grow subscribers and video views.",
    "h1": "AI Twitch Script & Promo Writer",
    "heroSubheading": "Generate attention-grabbing video scripts, hooks, and descriptions designed to keep viewers watching.",
    "introText": "Video and audio platforms are driven by watch time and retention. If your video hook is slow or boring, viewers swipe away in 3 seconds. PostMaker drafts quick, high-retention video script outlines, hooks, titles, and descriptions for Twitch to maximize CTR and keep viewers watching.",
    "audienceDescription": "Video creators, podcasters, stream hosts, and video editors seeking viral growth.",
    "formattingTip": "State the payoff in the first 3 seconds, structure scripts into hook-value-cta, and keep descriptions keyword-rich for search.",
    "postMakerVsGeneric": {
      "platformSpecific": "A structured script outline starting with a strong visual hook, followed by 3 key points and a quick CTA.",
      "genericCrossPost": "A dry, wordy script read that sounds like a textbook outline.",
      "explanation": "Online video feeds require conversational, fast-paced language. PostMaker drafts outlines that sound natural and high-energy."
    },
    "features": [
      {
        "title": "3-Second Hook Optimizer",
        "description": "Creates powerful visual and verbal openings that stop users from scrolling past your video."
      },
      {
        "title": "Visual Cue Prompts",
        "description": "Includes script suggestions for overlay text and visual shifts to maintain high viewer retention."
      },
      {
        "title": "SEO Description Sync",
        "description": "Optimizes video captions and search terms to match algorithm category search queries."
      }
    ],
    "faqs": [
      {
        "question": "How do I write a script hook that stops the scroll?",
        "answer": "Start in the middle of the action, address a major pain point immediately, or show the end result first to create curiosity."
      },
      {
        "question": "What is the optimal script structure for short video?",
        "answer": "Use the Hook (0-3s) -> Core Value/Story (3-45s) -> Call to Action (45-60s) layout for maximum retention."
      }
    ],
    "ctaText": "Generate Twitch Post"
  },
  {
    "slug": "clubhouse",
    "platformId": "clubhouse",
    "platformName": "Clubhouse",
    "title": "AI Clubhouse Script Outline & Video Description Writer | PostMaker",
    "description": "Write high-retention video hooks, script outlines, and descriptions for Clubhouse. Grow subscribers and video views.",
    "h1": "AI Clubhouse Script & Promo Writer",
    "heroSubheading": "Generate attention-grabbing video scripts, hooks, and descriptions designed to keep viewers watching.",
    "introText": "Video and audio platforms are driven by watch time and retention. If your video hook is slow or boring, viewers swipe away in 3 seconds. PostMaker drafts quick, high-retention video script outlines, hooks, titles, and descriptions for Clubhouse to maximize CTR and keep viewers watching.",
    "audienceDescription": "Video creators, podcasters, stream hosts, and video editors seeking viral growth.",
    "formattingTip": "State the payoff in the first 3 seconds, structure scripts into hook-value-cta, and keep descriptions keyword-rich for search.",
    "postMakerVsGeneric": {
      "platformSpecific": "A structured script outline starting with a strong visual hook, followed by 3 key points and a quick CTA.",
      "genericCrossPost": "A dry, wordy script read that sounds like a textbook outline.",
      "explanation": "Online video feeds require conversational, fast-paced language. PostMaker drafts outlines that sound natural and high-energy."
    },
    "features": [
      {
        "title": "3-Second Hook Optimizer",
        "description": "Creates powerful visual and verbal openings that stop users from scrolling past your video."
      },
      {
        "title": "Visual Cue Prompts",
        "description": "Includes script suggestions for overlay text and visual shifts to maintain high viewer retention."
      },
      {
        "title": "SEO Description Sync",
        "description": "Optimizes video captions and search terms to match algorithm category search queries."
      }
    ],
    "faqs": [
      {
        "question": "How do I write a script hook that stops the scroll?",
        "answer": "Start in the middle of the action, address a major pain point immediately, or show the end result first to create curiosity."
      },
      {
        "question": "What is the optimal script structure for short video?",
        "answer": "Use the Hook (0-3s) -> Core Value/Story (3-45s) -> Call to Action (45-60s) layout for maximum retention."
      }
    ],
    "ctaText": "Generate Clubhouse Post"
  },
  {
    "slug": "dribbble",
    "platformId": "dribbble",
    "platformName": "Dribbble",
    "title": "AI Dribbble Project Description & Tag Generator | PostMaker",
    "description": "Write search-optimized project descriptions and tag sets for Dribbble. Showcase your design portfolio and attract clients.",
    "h1": "AI Dribbble Description Writer",
    "heroSubheading": "Generate keyword-dense project descriptions that showcase your design work and attract clients.",
    "introText": "Visual portfolios on Dribbble require descriptions that explain the \"why\" and \"how\" behind the project to rank in search and showcase your expertise. PostMaker structures your design process, tool stacks, and credits into clear, scannable case studies that look premium and attract high-value clients.",
    "audienceDescription": "UI/UX designers, illustrators, branding experts, and creative studios building their portfolio.",
    "formattingTip": "Share the client brief, explain your creative solutions, detail the tools and fonts used, and add clean credits.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detailed project case study sharing the client challenge, stack, design solutions, and clear links for inquiries.",
      "genericCrossPost": "A simple title like \"Logo Design\" with no description or tags to explain the project.",
      "explanation": "Clients look for design thinking, not just final images. PostMaker helps you frame your design project as a professional case study."
    },
    "features": [
      {
        "title": "Case Study Outlining",
        "description": "Structures your project description into a mini case study: Brief -> Challenge -> Creative Solution."
      },
      {
        "title": "Tool & Credit Formatting",
        "description": "Cleanly lists the tools, fonts, colors, and team credits used in the design project."
      },
      {
        "title": "Creative Tag Suggesting",
        "description": "Generates high-traffic, relevant search tags to help your project rank in the platform directory."
      }
    ],
    "faqs": [
      {
        "question": "How can I attract design clients on Dribbble?",
        "answer": "Explain your process in detail in the description. Show how your design solved a real business problem for the client, and include contact details."
      },
      {
        "question": "What should I include in my project description?",
        "answer": "Include the project brief, key design decisions, software/tools used, team credits, and a call-to-action for new client inquiries."
      }
    ],
    "ctaText": "Generate Dribbble Post"
  },
  {
    "slug": "behance",
    "platformId": "behance",
    "platformName": "Behance",
    "title": "AI Behance Project Description & Tag Generator | PostMaker",
    "description": "Write search-optimized project descriptions and tag sets for Behance. Showcase your design portfolio and attract clients.",
    "h1": "AI Behance Description Writer",
    "heroSubheading": "Generate keyword-dense project descriptions that showcase your design work and attract clients.",
    "introText": "Visual portfolios on Behance require descriptions that explain the \"why\" and \"how\" behind the project to rank in search and showcase your expertise. PostMaker structures your design process, tool stacks, and credits into clear, scannable case studies that look premium and attract high-value clients.",
    "audienceDescription": "UI/UX designers, illustrators, branding experts, and creative studios building their portfolio.",
    "formattingTip": "Share the client brief, explain your creative solutions, detail the tools and fonts used, and add clean credits.",
    "postMakerVsGeneric": {
      "platformSpecific": "A detailed project case study sharing the client challenge, stack, design solutions, and clear links for inquiries.",
      "genericCrossPost": "A simple title like \"Logo Design\" with no description or tags to explain the project.",
      "explanation": "Clients look for design thinking, not just final images. PostMaker helps you frame your design project as a professional case study."
    },
    "features": [
      {
        "title": "Case Study Outlining",
        "description": "Structures your project description into a mini case study: Brief -> Challenge -> Creative Solution."
      },
      {
        "title": "Tool & Credit Formatting",
        "description": "Cleanly lists the tools, fonts, colors, and team credits used in the design project."
      },
      {
        "title": "Creative Tag Suggesting",
        "description": "Generates high-traffic, relevant search tags to help your project rank in the platform directory."
      }
    ],
    "faqs": [
      {
        "question": "How can I attract design clients on Behance?",
        "answer": "Explain your process in detail in the description. Show how your design solved a real business problem for the client, and include contact details."
      },
      {
        "question": "What should I include in my project description?",
        "answer": "Include the project brief, key design decisions, software/tools used, team credits, and a call-to-action for new client inquiries."
      }
    ],
    "ctaText": "Generate Behance Post"
  },
  {
    "slug": "telegram",
    "platformId": "telegram",
    "platformName": "Telegram",
    "title": "AI Telegram Message & Broadcast Formatter | PostMaker",
    "description": "Format clear, conversion-optimized messages and broadcast updates for Telegram. Boost announcement click-through rates.",
    "h1": "AI Telegram Message Writer",
    "heroSubheading": "Format clean message broadcasts and community updates that drive clicks and responses.",
    "introText": "Broadcast messaging on Telegram must be scannable, clear, and highly visual. Wall-of-text messages get ignored or muted. PostMaker structures your updates with clean bullet points, bold key phrases, and spaced emoji visual anchors to ensure your announcement is read and clicked immediately.",
    "audienceDescription": "Group administrators, brand managers, and community managers broadcasting updates.",
    "formattingTip": "Start with a clear, bold headline, use bullet points for announcement details, add double spaces, and place the CTA link on its own line.",
    "postMakerVsGeneric": {
      "platformSpecific": "A spaced message update starting with a bold headline, using bullet points, and placing the link clearly at the bottom.",
      "genericCrossPost": "A massive, single-paragraph text block with no spacing, making it difficult to read on a mobile screen.",
      "explanation": "Messaging apps are read on mobile screens. PostMaker applies visual spacing and emoji bullet points to drive message readability."
    },
    "features": [
      {
        "title": "Mobile Spacing Optimization",
        "description": "Applies double-line spaces and short sentences to prevent text blocks from looking dense on mobile."
      },
      {
        "title": "Emoji Visual Bullet Anchoring",
        "description": "Uses clear, professional emojis as bullet points to guide the reader's eye down to the link."
      },
      {
        "title": "CTA Link Isolation",
        "description": "Places call-to-action links on their own line with arrow pointers to maximize tap rates."
      }
    ],
    "faqs": [
      {
        "question": "How do I prevent users from muting my channel on Telegram?",
        "answer": "Keep updates short, highly scannable, deliver direct value (promotions, updates), and avoid spamming too many messages in a single day."
      },
      {
        "question": "What is the best layout for message broadcasts?",
        "answer": "Use a bold hook header -> 3 bullet points of details -> 1 direct action link on its own line."
      }
    ],
    "ctaText": "Generate Telegram Post"
  },
  {
    "slug": "slack",
    "platformId": "slack",
    "platformName": "Slack",
    "title": "AI Slack Message & Broadcast Formatter | PostMaker",
    "description": "Format clear, conversion-optimized messages and broadcast updates for Slack. Boost announcement click-through rates.",
    "h1": "AI Slack Message Writer",
    "heroSubheading": "Format clean message broadcasts and community updates that drive clicks and responses.",
    "introText": "Broadcast messaging on Slack must be scannable, clear, and highly visual. Wall-of-text messages get ignored or muted. PostMaker structures your updates with clean bullet points, bold key phrases, and spaced emoji visual anchors to ensure your announcement is read and clicked immediately.",
    "audienceDescription": "Group administrators, brand managers, and community managers broadcasting updates.",
    "formattingTip": "Start with a clear, bold headline, use bullet points for announcement details, add double spaces, and place the CTA link on its own line.",
    "postMakerVsGeneric": {
      "platformSpecific": "A spaced message update starting with a bold headline, using bullet points, and placing the link clearly at the bottom.",
      "genericCrossPost": "A massive, single-paragraph text block with no spacing, making it difficult to read on a mobile screen.",
      "explanation": "Messaging apps are read on mobile screens. PostMaker applies visual spacing and emoji bullet points to drive message readability."
    },
    "features": [
      {
        "title": "Mobile Spacing Optimization",
        "description": "Applies double-line spaces and short sentences to prevent text blocks from looking dense on mobile."
      },
      {
        "title": "Emoji Visual Bullet Anchoring",
        "description": "Uses clear, professional emojis as bullet points to guide the reader's eye down to the link."
      },
      {
        "title": "CTA Link Isolation",
        "description": "Places call-to-action links on their own line with arrow pointers to maximize tap rates."
      }
    ],
    "faqs": [
      {
        "question": "How do I prevent users from muting my channel on Slack?",
        "answer": "Keep updates short, highly scannable, deliver direct value (promotions, updates), and avoid spamming too many messages in a single day."
      },
      {
        "question": "What is the best layout for message broadcasts?",
        "answer": "Use a bold hook header -> 3 bullet points of details -> 1 direct action link on its own line."
      }
    ],
    "ctaText": "Generate Slack Post"
  },
  {
    "slug": "whatsapp",
    "platformId": "whatsapp",
    "platformName": "WhatsApp",
    "title": "AI WhatsApp Message & Broadcast Formatter | PostMaker",
    "description": "Format clear, conversion-optimized messages and broadcast updates for WhatsApp. Boost announcement click-through rates.",
    "h1": "AI WhatsApp Message Writer",
    "heroSubheading": "Format clean message broadcasts and community updates that drive clicks and responses.",
    "introText": "Broadcast messaging on WhatsApp must be scannable, clear, and highly visual. Wall-of-text messages get ignored or muted. PostMaker structures your updates with clean bullet points, bold key phrases, and spaced emoji visual anchors to ensure your announcement is read and clicked immediately.",
    "audienceDescription": "Group administrators, brand managers, and community managers broadcasting updates.",
    "formattingTip": "Start with a clear, bold headline, use bullet points for announcement details, add double spaces, and place the CTA link on its own line.",
    "postMakerVsGeneric": {
      "platformSpecific": "A spaced message update starting with a bold headline, using bullet points, and placing the link clearly at the bottom.",
      "genericCrossPost": "A massive, single-paragraph text block with no spacing, making it difficult to read on a mobile screen.",
      "explanation": "Messaging apps are read on mobile screens. PostMaker applies visual spacing and emoji bullet points to drive message readability."
    },
    "features": [
      {
        "title": "Mobile Spacing Optimization",
        "description": "Applies double-line spaces and short sentences to prevent text blocks from looking dense on mobile."
      },
      {
        "title": "Emoji Visual Bullet Anchoring",
        "description": "Uses clear, professional emojis as bullet points to guide the reader's eye down to the link."
      },
      {
        "title": "CTA Link Isolation",
        "description": "Places call-to-action links on their own line with arrow pointers to maximize tap rates."
      }
    ],
    "faqs": [
      {
        "question": "How do I prevent users from muting my channel on WhatsApp?",
        "answer": "Keep updates short, highly scannable, deliver direct value (promotions, updates), and avoid spamming too many messages in a single day."
      },
      {
        "question": "What is the best layout for message broadcasts?",
        "answer": "Use a bold hook header -> 3 bullet points of details -> 1 direct action link on its own line."
      }
    ],
    "ctaText": "Generate WhatsApp Post"
  },
  {
    "slug": "lemon8",
    "platformId": "lemon8",
    "platformName": "Lemon8",
    "title": "AI Lemon8 Caption & Short Post Writer | PostMaker",
    "description": "Craft high-impact, short-form posts and captions for Lemon8. Drive replies, retweets, and follower growth with clean copy.",
    "h1": "AI Lemon8 Post Creator",
    "heroSubheading": "Generate punchy, high-engagement updates and short posts optimized for Lemon8.",
    "introText": "Short-form feeds require writing that is concise, impactful, and immediately conversational. PostMaker translates your core ideas into punchy, scroll-stopping updates that fit within the platform limitations of Lemon8, boosting impressions, likes, and shares.",
    "audienceDescription": "Content creators, personal brands, and social media managers posting updates on the go.",
    "formattingTip": "Make the first line punchy, use spacing to break up phrases, keep the tone casual, and place tags neatly at the end if applicable.",
    "postMakerVsGeneric": {
      "platformSpecific": "A short, high-signal observation or question that reads naturally and invites immediate replies.",
      "genericCrossPost": "A copy-paste of a long blog paragraph that gets cut off or looks too formal for a quick feed.",
      "explanation": "Lemon8 users browse quickly. Short, conversational thoughts generate far more interaction than generic copy."
    },
    "features": [
      {
        "title": "Concise Compression",
        "description": "Compresses ideas into high-signal sentences that deliver maximum impact in minimal characters."
      },
      {
        "title": "Interactive Prompters",
        "description": "Finishes updates with natural prompts or questions to stimulate the comment section."
      },
      {
        "title": "Native Feed Styling",
        "description": "Outputs formatting, emojis, and hashtags that match the exact visual style and limits of Lemon8."
      }
    ],
    "faqs": [
      {
        "question": "What is the character limit for Lemon8?",
        "answer": "PostMaker automatically respects Lemon8's exact character and media limit rules so your post is always ready to publish."
      },
      {
        "question": "How do I get more reach on Lemon8?",
        "answer": "Keep posts short, spark comments with open-ended questions, and write posts that invite users to bookmark or share."
      }
    ],
    "ctaText": "Generate Lemon8 Post"
  }
];
